### ISSUE TITLE
[Application] Application 프로세스 네임 지정 및 Hardware Vendor 식별 기능 추가

### ISSUE THREAD

**Issue by Hamsik2rang** [Hamsik2rang/Kepler#48]
## 배경
* 현재 모든 Application은 "Kepler Engine"으로 프로세스명이 지정됨
* 어플리케이션을 실행하는 Client의 HW Vendor 식별(GPU, CPU 등)이 이루어지지 않음
## 목표
* 원하는 이름을 지정할 수 있도록 간단한 기능 추가
* HW Vendor Info를 Context생성 시 로깅하도록 간단한 기능 추가

**Comment by MistarJo** [comment]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/51068131/181432236-31e97edf-6fcd-47b8-9d74-e78e26e7f99a.png">

**Comment by Hamsik2rang** [comment]
@MistarJo 👍👍 Pull Request 하세용

**Comment by Hamsik2rang** [comment]
Issue 닫습니당
